#!/bin/sh
name=gendesk
version=$(grep version main.go | head -1 | cut -d\" -f2 | cut -d. -f2-)
mkdir "$name-$version"
cp -r $name.1 *.go LICENSE vendor "$name-$version/"
gzip "$name-$version/$name.1"
tar Jcf "$name-$version.tar.xz" "$name-$version/"
rm -r "$name-$version"
