#!/bin/sh
name=gendesk
version=$(grep version main.go | head -1 | sed 's/\"//g' | tr ' ' '\n' | tail -1)

# goreleaser: go get -u github.com/goreleaser/goreleaser
goreleaser --skip-publish --rm-dist

# source tarball
mkdir "$name-$version"
cp -r $name.1 *.go LICENSE vendor "$name-$version/"
gzip "$name-$version/$name.1"
tar Jcf "dist/$name-$version.tar.xz" "$name-$version/"
rm -r "$name-$version"
